### ISSUE TITLE
BUG: Cannot enter Knob values

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/fmsite#24] opened 2022-07-27 20:23 UTC
IDK whether this should be on Knob or on Piano, but the knobs do not allow you to enter values, since they are intercepted by the Piano. We need to fix this.

**Comment by neonfuz** [comment] 2022-07-27 20:30
@44100hertz Check `document.activeElement instanceof HTMLInputElement` to check if the currently focused element is an <input> and don't preventDefault.

https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement

**Comment by 44100hertz** [comment] 2022-07-27 20:39
Duplicate of #14

**Comment by neonfuz** [comment] 2022-07-27 23:00
Closed the duplicate, solve this here.

**Closed** 2022-07-29 19:51 UTC
Labels: bug
