### ISSUE TITLE
Volume knob from -72dB to 0dB is backwards.

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fmsite#8] opened 2022-07-21 07:23 UTC
This is an isssue in the DJ Knob module.

**Comment by neonfuz** [comment] 2022-07-21 13:05
This issue is in the DumbKnob component you wrote so actually you should fix this

**Comment by neonfuz** [comment] 2022-08-09 01:00
Volume knob is gone, but the MinimalKnob still draws backwards, even after the rebase.

**Comment by neonfuz** [comment] 2022-08-09 01:01
Closing because the issue is on the wrong repo.

**Closed by neonfuz** 2022-08-09 01:01 UTC
Labels: bug
